version: "3.3"
services:
  web-server:
    build:
      dockerfile: Dockerfile
      context: .
    restart: always
    user: 1000:1000
    volumes:
      - "./app/:/var/www/html:cached"
    ports:
      - "8081:80"
    networks:
      - net-opencart
  mysql-server:
    image: mysql:8.0
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - ./volumes/mysql:/var/lib/mysql
      - ./log/mysql:/var/log/mysql
    networks:
      - net-opencart

networks:
  net-opencart:
    driver: bridge